cd ~ && \
git clone https://github.com/Achi-Coin/achi-blockchain && cd achi-blockchain && sh install.sh && . ./activate && achi init && achi init --fix-ssl-permissions ; achi keys add -f ~/keys/key.txt &&  deactivate && cd .. && \
git clone https://github.com/AedgeCoin/aedge-blockchain && cd aedge-blockchain && sh install.sh && . ./activate && aedge init && aedge init --fix-ssl-permissions ; aedge keys add -f ~/keys/key.txt &&  deactivate && cd .. && \
git clone https://github.com/Apple-Network/apple-blockchain && cd apple-blockchain && sh install.sh && . ./activate && apple init && apple init --fix-ssl-permissions ; apple keys add -f ~/keys/key.txt &&  deactivate && cd .. && \
git clone https://github.com/Avocado-Network/avocado-blockchain && cd avocado-blockchain && sh install.sh && . ./activate && avocado init && avocado init && avocado init --fix-ssl-permissions ; avocado keys add -f ~/keys/key.txt &&  deactivate && cd .. && \
git clone https://github.com/bpx-network/bpx-blockchain.git && cd bpx-blockchain && sh install.sh && . ./activate && bpx init && bpx init --fix-ssl-permissions ; bpx keys add -f ~/keys/key.txt && deactivate && cd .. && \
git clone https://github.com/BTCgreen-Network/btcgreen-blockchain && cd btcgreen-blockchain && sh install.sh && . ./activate && btcgreen init && btcgreen init --fix-ssl-permissions ; btcgreen keys add -f ~/keys/key.txt &&  deactivate && cd .. && \
git clone https://github.com/Cactus-Network/cactus-blockchain && cd cactus-blockchain && sh install.sh && . ./activate && cactus init && cactus init --fix-ssl-permissions ; cactus keys add -f ~/keys/key.txt  && deactivate && cd .. && \
git clone https://github.com/CannabisChain/cannabis-blockchain && cd cannabis-blockchain && sh install.sh && . ./activate && cannabis init && cannabis init --fix-ssl-permissions ; cannabis keys add -f ~/keys/key.txt && deactivate && cd .. && \
git clone https://github.com/Chinilla/chinilla-blockchain && cd chinilla-blockchain && sh install.sh && . ./activate && chinilla init && chinilla init --fix-ssl-permissions && chinilla init -c ~/chinilla-ca/ ; chinilla keys add -f ~/keys/key.txt && deactivate && cd .. && \
git clone https://github.com/HiveProject2021/chives-blockchain && cd chives-blockchain && sh install.sh && . ./activate && chives init && chives init --fix-ssl-permissions ; chives keys add -f ~/keys/chives-key.txt &&  deactivate && cd .. && \
git clone https://github.com/Chia-Network/chia-blockchain && cd chia-blockchain && sh install.sh && . ./activate && chia init && chia init --fix-ssl-permissions ; chia keys add -f ~/keys/key.txt && deactivate && cd .. && \
git clone https://github.com/CryptoDoge-Network/cryptodoge && cd cryptodoge && sh install.sh && . ./activate && cryptodoge init && cryptodoge init --fix-ssl-permissions ; cryptodoge keys add -f ~/keys/key.txt &&  deactivate && cd .. && \
git clone https://github.com/Cunt-Network/cunt-blockchain && cd cunt-blockchain && sh install.sh && . ./activate && cunt init && cunt init --fix-ssl-permissions ; cunt keys add -f ~/keys/key.txt &&  deactivate && cd .. && \
git clone https://github.com/DogeChia/doge-chia && cd doge-chia && sh install.sh && . ./activate && dogechia init && dogechia init --fix-ssl-permissions ; dogechia keys add -f ~/keys/key.txt &&  deactivate && cd .. && \
git clone https://github.com/Ecostake-Network/ecostake-blockchain && cd ecostake-blockchain && sh install.sh && . ./activate && ecostake init && ecostake init --fix-ssl-permissions && ecostake init -c ~/ecostake-ca/ ; ecostake keys add -f ~/keys/key.txt && deactivate && cd .. && \
git clone https://github.com/ethgreen/ethgreen-blockchain && cd ethgreen-blockchain && sh install.sh && . ./activate && ethgreen init && ethgreen init --fix-ssl-permissions ; ethgreen keys add -f ~/keys/key.txt && deactivate && cd .. && \
git clone https://gitlab.com/fisheryffk/fishery-blockchain && cd fishery-blockchain && sh install.sh && . ./activate && fishery init && fishery init --fix-ssl-permissions ; fishery keys add -f ~/keys/fishery-key.txt &&  deactivate && cd .. && \
git clone https://github.com/Flax-Network/flax-blockchain && cd flax-blockchain && sh install.sh && . ./activate && flax init && flax init --fix-ssl-permissions ; flax keys add -f ~/keys/key.txt &&  deactivate && cd .. && \
git clone https://github.com/Flora-Network/flora-blockchain && cd flora-blockchain && sh install.sh && . ./activate && flora init && flora init --fix-ssl-permissions ; flora keys add -f ~/keys/key.txt &&  deactivate && cd .. && \
git clone https://github.com/zcomputerwiz/goji-blockchain && cd goji-blockchain && sh install.sh && . ./activate && goji init && goji init --fix-ssl-permissions ; goji keys add -f ~/keys/key.txt && deactivate && cd .. && \
git clone https://github.com/goldcoin-gl/gold-blockchain && cd gold-blockchain && sh install.sh && . ./activate && gold init && gold init --fix-ssl-permissions ; gold keys add -f ~/keys/key.txt &&  deactivate && cd .. && \
git clone https://github.com/GreenDoge-Network/greendoge-blockchain && cd greendoge-blockchain && sh install.sh && . ./activate && greendoge init && greendoge init --fix-ssl-permissions ; greendoge keys add -f ~/keys/key.txt &&  deactivate && cd .. && \
git clone https://github.com/HDDcoin-Network/hddcoin-blockchain && cd hddcoin-blockchain && sh install.sh && . ./activate && hddcoin init && hddcoin init --fix-ssl-permissions ; hddcoin keys add -f ~/keys/key.txt &&  deactivate && cd .. && \
git clone https://github.com/Kale-Network/kale-blockchain && cd kale-blockchain && sh install.sh && . ./activate && kale init && kale init --fix-ssl-permissions ; kale keys add -f ~/keys/key.txt &&  deactivate && cd .. && \
git clone https://github.com/BTCgreen-Network/littlelambocoin-blockchain && cd littlelambocoin-blockchain && sh install.sh && . ./activate && littlelambocoin init && littlelambocoin init --fix-ssl-permissions ; littlelambocoin keys add -f ~/keys/key.txt &&  deactivate && cd .. && \
git clone https://github.com/KiwiNetworkOrg/kiwi-blockchain && cd kiwi-blockchain && sh install.sh && . ./activate && kiwi init && kiwi init --fix-ssl-permissions ; kiwi keys add -f ~/keys/key.txt &&  deactivate && cd .. && \
git clone https://github.com/Kujenga-Network/kujenga-blockchain && cd kujenga-blockchain && sh install.sh && . ./activate && kujenga init && kujenga init --fix-ssl-permissions ; kujenga keys add -f ~/keys/key.txt &&  deactivate && cd .. && \
git clone https://github.com/gowke/lotus-blockchain && cd lotus-blockchain && sh install.sh && . ./activate && lotus init && lotus init --fix-ssl-permissions ; lotus keys add -f ~/keys/key.txt &&  deactivate && cd .. && \
git clone https://github.com/dream80/lucky-blockchain -b v1.2.10.10 && cd lucky-blockchain && sh install.sh && . ./activate && lucky init && lucky init --fix-ssl-permissions ; lucky keys add -f ~/keys/key.txt &&  deactivate && cd .. && \
git clone https://github.com/Maize-Network/maize-blockchain && cd maize-blockchain && sh install.sh && . ./activate && maize init && maize init --fix-ssl-permissions ; maize keys add -f ~/keys/key.txt &&  deactivate && cd .. && \
git clone https://github.com/Melati-Network/melati-blockchain && cd melati-blockchain && sh install.sh && . ./activate && melati init && melati init --fix-ssl-permissions ; melati keys add -f ~/keys/key.txt &&  deactivate && cd .. && \
git clone https://github.com/mELON-Network/melon-blockchain && cd melon-blockchain && sh install.sh && . ./activate && melon init && melon init --fix-ssl-permissions ; melon keys add -f ~/keys/key.txt &&  deactivate && cd .. && \
git clone https://github.com/MintNetwork/mint-blockchain && cd mint-blockchain && sh install.sh && . ./activate && mint init && mint init --fix-ssl-permissions ; mint keys add -f ~/keys/key.txt &&  deactivate && cd .. && \
git clone https://github.com/mogua-network/mogua-blockchain && cd mogua-blockchain && sh install.sh && . ./activate && mogua init && mogua init --fix-ssl-permissions ; mogua keys add -f ~/keys/key.txt &&  deactivate && cd .. && \
git clone https://github.com/MOONCOINTEAM/moon-blockchain && cd moon-blockchain && sh install.sh && . ./activate && moon init && moon init --fix-ssl-permissions ; moon keys add -f ~/keys/key.txt && deactivate && cd .. && \
git clone https://gitee.com/ext9/ext9-blockchain && cd ext9-blockchain && sh install.sh && . ./activate && chia init && chia init --fix-ssl-permissions ; chia keys add -f ~/keys/key.txt &&  deactivate && cd .. && \
git clone https://github.com/Petroleum-Network/petroleum-blockchain/ && cd petroleum-blockchain && sh install.sh && . ./activate && petroleum init && petroleum init --fix-ssl-permissions ; petroleum keys add -f ~/keys/key.txt &&  deactivate && cd .. && \
git clone https://github.com/Olive-blockchain/Olive-blockchain && cd Olive-blockchain && sh install.sh && . ./activate && olive init && olive init --fix-ssl-permissions ; olive keys add -f ~/keys/key.txt &&  deactivate && cd .. && \
# ===>>> UNOFFICIAL VERSION of peas. replacing the official non functioning version <<<===git clone https://github.com/SupermanPea/peas-blockchain && cd peas-blockchain && sh install.sh && . ./activate && peas init && peas init --fix-ssl-permissions ; peas keys add -f ~/keys/key.txt &&  deactivate && cd .. && \
git clone https://github.com/13thProgression/peas-blockchain && cd peas-blockchain && sh install.sh && . ./activate && peas init && peas init --fix-ssl-permissions ; peas keys add -f ~/keys/key.txt &&  deactivate && cd .. && \
git clone https://github.com/Pipscoin-Network/pipscoin-blockchain && cd pipscoin-blockchain && sh install.sh && . ./activate && pipscoin init && pipscoin init --fix-ssl-permissions ; pipscoin keys add -f ~/keys/key.txt &&  deactivate && cd .. && \
git clone https://github.com/ProfitCrypto/profit-blockchain && cd profit-blockchain && sh install.sh && . ./activate && profit init && profit init --fix-ssl-permissions ; profit keys add -f ~/keys/key.txt &&  deactivate && cd .. && \
git clone https://github.com/Salvia-Network/salvia-blockchain && cd salvia-blockchain && sh install.sh && . ./activate && salvia init && salvia init --fix-ssl-permissions ; salvia keys add -f ~/keys/key.txt &&  deactivate && cd .. && \
git clone https://github.com/VRn00b/scam-blockchain && cd scam-blockchain && sh install.sh && . ./activate && scam init && scam init --fix-ssl-permissions ; scam keys add -f ~/keys/key.txt &&  deactivate && cd .. && \
git clone https://github.com/denisio/seno-blockchain && cd seno-blockchain && sh install.sh && . ./activate && seno init && seno init --fix-ssl-permissions ; seno keys add -f ~/keys/key.txt &&  deactivate && cd .. && \
git clone https://github.com/btcgreen-network/shibgreen-blockchain && cd shibgreen-blockchain && sh install.sh && . ./activate && shibgreen init && shibgreen init --fix-ssl-permissions ; shibgreen keys add -f ~/keys/key.txt && deactivate && cd .. && \
git clone https://github.com/Sector-Network/sector-blockchain && cd sector-blockchain && sh install.sh && . ./activate && sector init && sector init --fix-ssl-permissions ; sector keys add -f ~/keys/key.txt &&  deactivate && cd .. && \
git clone https://github.com/silicoin-network/silicoin-blockchain && cd silicoin-blockchain && sh install.sh && . ./activate && sit init && sit init --fix-ssl-permissions ; sit keys add -f ~/keys/key.txt && deactivate && cd .. && \
git clone https://bitbucket.org/Socks-Network/socks-blockchain && cd socks-blockchain && sh install.sh && . ./activate && socks init && socks init --fix-ssl-permissions ; socks keys add -f ~/keys/key.txt &&  deactivate && cd .. && \
git clone https://github.com/SkynetNetwork/skynet-blockchain && cd skynet-blockchain && sh install.sh && . ./activate && skynet init && skynet init --fix-ssl-permissions ; skynet keys add -f ~/keys/key.txt &&  deactivate && cd .. && \
git clone https://github.com/zcomputerwiz/sparev2-blockchain && cd sparev2-blockchain && sh install.sh && . ./activate && spare init && spare init --fix-ssl-permissions ; spare keys add -f ~/keys/key.txt &&  deactivate && cd .. && \
git clone https://github.com/STATION-I/stai-blockchain && cd stai-blockchain && sh install.sh && . ./activate && stai init && stai init --fix-ssl-permissions ; stai keys add -f ~/keys/key.txt &&  deactivate && cd .. && \
git clone https://github.com/Stor-Network/stor-blockchain && cd stor-blockchain && sh install.sh && . ./activate && stor init && stor init --fix-ssl-permissions ; stor keys add -f ~/keys/key.txt &&  deactivate && cd .. && \
git clone https://github.com/Taco-Network/taco-blockchain && cd taco-blockchain && sh install.sh && . ./activate && taco init && taco init --fix-ssl-permissions ; taco keys add -f ~/keys/key.txt &&  deactivate && cd .. && \
git clone https://github.com/BTCgreen-Network/tad-blockchain && cd tad-blockchain && sh install.sh && . ./activate && tad init && tad init --fix-ssl-permissions ; tad keys add -f ~/keys/key.txt &&  deactivate && cd .. && \
git clone https://github.com/Tranzact-Network/tranzact-blockchain && cd tranzact-blockchain && sh install.sh && . ./activate && tranzact init && tranzact init --fix-ssl-permissions ; tranzact keys add -f ~/keys/key.txt &&  deactivate && cd .. && \
git clone https://github.com/Venidium-Network/venidium-blockchain && cd venidium-blockchain && sh install.sh && . ./activate && venidium init && venidium init --fix-ssl-permissions ; venidium keys add -f ~/keys/key.txt && deactivate && cd .. && \
git clone https://github.com/wheatnetwork/wheat-blockchain && cd wheat-blockchain && sh install.sh && . ./activate && wheat init && wheat init --fix-ssl-permissions ; wheat keys add -f ~/keys/key.txt && deactivate && cd .. && \
git clone https://github.com/xchaio/xcha-blockchain && cd xcha-blockchain && sh install.sh && . ./activate && xcha init && xcha init --fix-ssl-permissions ; xcha keys add -f ~/keys/key.txt && deactivate && cd .. && \
git clone https://github.com/strandedathome/rolls-blockchain && cd rolls-blockchain && sh install.sh && . ./activate && rolls init && rolls init --fix-ssl-permissions ; rolls keys add -f ~/keys/key.txt && deactivate && cd .. && \

#Install Forktools and Pitchfork:
cd ~ && git clone https://github.com/Qwinn1/forktools && cd forktools && sudo apt install curl -y && bash installft.sh && source ~/.bashrc && cd .. && \
git clone https://github.com/ageorge95/pitchFORK-chia-forks-ports-check  && cd pitchFORK-chia-forks-ports-check
